# Generated by Django 6.0.4 on 2026-08-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEOUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email manzil')),
                ('password_hash', models.CharField(max_length=256, verbose_name='Parol (hash)')),
                ('full_name', models.CharField(max_length=150, verbose_name="To'liq ism")),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CEO / Platform Admin',
                'verbose_name_plural': 'CEO Foydalanuvchilar',
                'db_table': 'tenants_ceo_user',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Masalan: 'Najot Ta'lim', 'Ustoz Academy'", max_length=100, verbose_name="O'quv markaz nomi")),
                ('schema_name', models.CharField(help_text="Faqat kichik harf, raqam va '_' — masalan: tenant_najot", max_length=63, unique=True, verbose_name='PostgreSQL schema nomi')),
                ('is_active', models.BooleanField(default=True, help_text="False bo'lsa markaz bloklangan hisoblanadi", verbose_name='Faolmi?')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Aloqa telefon raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "O'quv Markaz",
                'verbose_name_plural': "O'quv Markazlar",
                'db_table': 'tenants_tenant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter — Asosiy'), ('pro', 'Pro — Kengaytirilgan'), ('enterprise', 'Enterprise — Korporativ')], default='starter', max_length=20, verbose_name='Tarif rejasi')),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oylik to'lov (so'm)")),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Obuna boshlangan sana')),
                ('expires_at', models.DateTimeField(verbose_name='Obuna tugash sanasi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('trial', 'Sinov davri'), ('expired', 'Muddati tugagan'), ('suspended', "To'xtatilgan")], default='trial', max_length=20, verbose_name='Obuna holati')),
                ('max_students', models.PositiveIntegerField(default=500, verbose_name="Maksimal o'quvchilar soni")),
                ('max_branches', models.PositiveIntegerField(default=1, verbose_name='Maksimal filiallar soni')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant', verbose_name="O'quv markaz")),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'db_table': 'tenants_subscription',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Masalan: najot.crm.uz (port raqamisiz)', max_length=253, unique=True, verbose_name='Domen')),
                ('is_primary', models.BooleanField(default=True, help_text="Har bir tenant uchun faqat bitta asosiy domen bo'lishi kerak", verbose_name='Asosiy domenmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant', verbose_name="O'quv markaz")),
            ],
            options={
                'verbose_name': 'Domen',
                'verbose_name_plural': 'Domenlar',
                'db_table': 'tenants_domain',
            },
        ),
    ]
