# Generated by Django 6.0.8 on 2026-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text="Ushbu o'quv markazining shaxsiy Telegram bot tokeni (ixtiyoriy)", max_length=150, null=True, verbose_name='Telegram Bot Token'),
        ),
    ]
