# Generated by Django 6.0.8 on 2026-09-26 16:05

import config.validators
import groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0028_group_groups_grou_name_0806de_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=groups.models.tenant_student_image_path, validators=[config.validators.validate_image_file]),
        ),
    ]
