# Generated by Django 6.0.8 on 2026-10-04 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_color'),
        ('groups', '0030_alter_student_address_alter_student_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='group',
            name='groups_grou_start_d_bf111c_idx',
        ),
        migrations.AddField(
            model_name='group',
            name='custom_days',
            field=models.JSONField(blank=True, default=list, help_text="Hafta kunlarining Python weekday indekslari ro'yxati: 0=Dushanba, 1=Seshanba, 2=Chorshanba, 3=Payshanba, 4=Juma, 5=Shanba, 6=Yakshanba", verbose_name='Hafta kunlari (custom)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='days',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dars kunlari turi (deprecated)'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['start_date'], name='groups_grou_start_d_71e5f5_idx'),
        ),
    ]
