# Generated by Django 6.0.8 on 2026-10-04 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0031_add_custom_days_jsonfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-id']},
        ),
    ]
