# Generated by Django 6.0.8 on 2026-09-26 16:05

import finance.models.student_payment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_financetransaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=finance.models.student_payment.tenant_receipt_image_path),
        ),
    ]
