# Generated by Django 6.0.8 on 2026-09-26 16:05

import authenticatsiya.models
import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticatsiya', '0006_usermodel_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=authenticatsiya.models.tenant_user_image_path, validators=[config.validators.validate_image_file]),
        ),
    ]
