# Generated by Django 6.0.8 on 2026-09-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticatsiya', '0007_alter_usermodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-id']},
        ),
    ]
