# Generated by Django 6.0.8 on 2026-09-26 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_alter_student_image'),
        ('homework_attends', '0012_alter_attendanceeditlog_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'group', 'date'), name='unique_daily_student_attendance'),
        ),
    ]
