# Generated by Django 6.0.8 on 2026-09-28 17:18

import django.core.validators
import homework_attends.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_attends', '0013_attendance_unique_daily_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=homework_attends.models.tenant_homework_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='Topshiriq fayli'),
        ),
    ]
