# Generated by Django 6.0.8 on 2026-09-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('mentor', 'Mentor'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20, verbose_name='Rol'),
        ),
    ]
